### ISSUE TITLE
cloud-kernel 改造成golang项目是不是好一点

### ISSUE THREAD

**Issue by cuisongliu** [fanux/cloud-kernel#40]
RT
打包时候调用一个二进制就好了，这块只是自动发版，把脚本封装一下？

**Comment by oldthreefeng** [comment]
感觉可以搞一搞. @cuisongliu 

其实每次修改这个仓库很蛋疼, 打包生成的脚本都要去修改. 而且已经发布的有可能需要重新发布.

**Comment by oldthreefeng** [comment]
感觉4.0 解决一切.  

3.0x 版本目前build的其实可以写在sealos里面.
